CREATE TABLE IF NOT EXISTS users (
  email VARCHAR PRIMARY KEY,
  user_name VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  admin INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS authors (
  author_name VARCHAR PRIMARY KEY);

CREATE TABLE IF NOT EXISTS documents (
  title VARCHAR PRIMARY KEY,
  author_name VARCHAR NOT NULL,
  content VARCHAR NOT NULL,
  FOREIGN KEY(author_name) REFERENCES authors(author_name));